name: Archive RPM

on:
  push:
    tags:
    - 'v*'
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    container: centos
    steps:
      - uses: actions/checkout@v2

      - name: Build rpm packages
        run: |
          yum install -y python3 rpm-build
          python3 setup.py bdist_rpm

      - name: Install additional dependencies
        run: |
          yum install -y createrepo git-core tree

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update rpm directory
        working-directory: gh-pages
        run: |
          cp ../dist/*.rpm rpm/
          rm -rf rpm/repodata/
          createrepo rpm/
          tree -h -F -I 'index.html' -H '.' -T 'python-shukujitsu / rpm' -L 1 --noreport --charset utf-8 rpm/ > rpm/index.html

      - name: Commit & Push
        working-directory: gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          tree -I .git
          git add --verbose --all rpm/
          git add --verbose --all rpm/repodata/
          git commit --verbose -m "Update rpm via $GITHUB_REF"
          git push origin gh-pages
