name: RPM and DEB

on:
  push:
    tags:
    - 'v*'
    branches: [ main ]

jobs:
  build_and_push_rpm:
    runs-on: ubuntu-latest
    container: centos
    steps:
      - uses: actions/checkout@v2

      - name: Build rpm packages
        run: |
          yum install -y python3 rpm-build
          python3 setup.py bdist_rpm

      - name: Install additional dependencies
        run: |
          yum install -y createrepo git-core rpm-sign tree

      - name: Sign rpm packages
        run: |
          rpm --import https://sakurai-youhei.github.io/python-shukujitsu/gpg
          cat <<EOF | gpg --batch --import
          ${{ secrets.GPG_PRIVATE_KEY }}
          EOF
          cat <<EOF > $HOME/.rpmmacros
          %_signature gpg
          %_gpg_path $HOME/.gnupg
          %_gpg_name Youhei Sakurai
          %_gpgbin /usr/bin/gpg
          %__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --batch --verbose --no-armor --passphrase-fd 0 --pinentry-mode loopback --no-secmem-warning -u '%{_gpg_name}' -sbo %{__signature_filename} %{__plaintext_filename}
          EOF
          echo | rpmsign --addsign dist/*.rpm

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update rpm directory
        working-directory: gh-pages
        run: |
          cp ../dist/*.rpm rpm/
          rm -rf rpm/repodata/
          createrepo rpm/
          tree -h -F -I 'index.html' -H '.' -T 'python-shukujitsu / rpm' -L 1 --noreport --charset utf-8 rpm/ > rpm/index.html
          tree -h -F -I 'index.html' -H '.' -T 'python-shukujitsu / rpm / repodata' -L 1 --noreport --charset utf-8 rpm/repodata/ > rpm/repodata/index.html

      - name: Commit & Push
        working-directory: gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          tree -I .git
          git add --verbose --all rpm/
          git add --verbose --all --force rpm/repodata/  # TODO: Remove '--force' option somehow.
          git commit --verbose -m "Update rpm via $GITHUB_REF"
          git push origin gh-pages

  build_and_push_deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build deb packages
        run: |
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y debhelper python3-all python3-setuptools python3-pip dh-python
          pip3 install --user stdeb
          python3 setup.py --command-packages=stdeb.command bdist_deb sdist_dsc
