name: RPM and DEB

on:
  push:
    tags:
    - 'v*'
    branches: [ main ]

jobs:
  build_and_push_rpm:
    runs-on: ubuntu-latest
    container: centos
    steps:
      - uses: actions/checkout@v2

      - name: Build rpm packages
        run: |
          yum install -y python3 rpm-build
          python3 setup.py bdist_rpm

      - name: Install additional dependencies
        run: |
          yum install -y createrepo git-core tree

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update rpm directory
        working-directory: gh-pages
        run: |
          cp ../dist/*.rpm rpm/
          rm -rf rpm/repodata/
          createrepo rpm/
          tree -h -F -I 'index.html' -H '.' -T 'python-shukujitsu / rpm' -L 1 --noreport --charset utf-8 rpm/ > rpm/index.html
          tree -h -F -I 'index.html' -H '.' -T 'python-shukujitsu / rpm / repodata' -L 1 --noreport --charset utf-8 rpm/repodata/ > rpm/repodata/index.html

      - name: Commit & Push
        working-directory: gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          tree -I .git
          git add --verbose --all rpm/
          git add --verbose --all --force rpm/repodata/  # TODO: Remove '--force' option somehow.
          git commit --verbose -m "Update rpm via $GITHUB_REF"
          git push origin gh-pages

  build_and_push_deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build deb packages
        run: |
          DEBIAN_FRONTEND=noninteractive apt install -y debhelper python3-all python3-pip dh-python
          pip3 install stdeb
          python3 setup.py --command-packages=stdeb.command bdist_deb sdist_dsc
